export { default as Home } from "./Home"
export { default as Category } from "./Category"
export { default as ForgetPassword } from "./ForgetPassword"
export { default as ResetPassword } from "./ResetPassword"
export { default as Login } from "./Login"
export { default as Register } from "./Register"
export { default as Pagenotfound } from "./Pagenotfound"
export { default as Protected } from "./Protected"